version: '3.4'
services:
  db:
    volumes:
      - ./volumes/database:/var/lib/postgresql/13
      - ./volumes/backups:/backups

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/cache:/home/web/cache

  worker:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/cache:/home/web/cache

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    ports:
      - "${HTTP_PORT:-8080}:80"
    links:
      - django

  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    container_name: "${COMPOSE_PROJECT_NAME}_dev"
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/cache:/home/web/cache
    ports:
      # for django test server
      - "2000:8080"
      # for ssh
      - "2001:22"
    entrypoint: [ ]
    profiles: [ "dev" ]